# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

env: 
  name: test
  url: https://github.com


jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download Files and Get Paths
        run: |
          # Array to store GIF URLs
          gif_urls=()

          # Get the list of GIF files in the img directory
          files=$(curl -sSL -H "Authorization: token ${{ secrets.RESOURCE_TOKEN }}" "https://api.github.com/repos/HKEYLOCALMACHINE/img" | jq -r '.[] | select(.type? == "file" and (.name | endswith(".gif"))) | .download_url')

          for file_url in $files; do
            response=$(curl -sSL -H "Authorization: token ${{ secrets.RESOURCE_TOKEN }}" -o $(basename $file_url) -w "%{url_effective}" $file_url)
            echo "$response"
            gif_urls+=("$response")
            done
          echo "GIF_URLS=${gif_urls[@]}" >> $GITHUB_ENV
          echo "GIF URLs: ${{ env.GIF_URLS }}"
       

